### ISSUE TITLE
isShowingMainView() should be public

### ISSUE THREAD

**Issue by hanggrian** [truizlop/FABRevealLayout#10]
Otherwise, there is no way to detect the state of the layout. Which is crucially important to hide the revealed layout `onBackPressed()`.

**Comment by truizlop** [comment]
Take a look at [OnRevealChangeListener](https://github.com/truizlop/FABRevealLayout/blob/master/library/src/main/java/com/truizlop/fabreveallayout/OnRevealChangeListener.java), which notifies you when either of the views has become visible.
