### ISSUE TITLE
Animation of image

### ISSUE THREAD

**Issue by fukemy** [truizlop/FABRevealLayout#12]
Hello. can i ask you what is your animation you used in this gif image:
https://github.com/truizlop/FABRevealLayout/raw/master/art/fabrl_qotsa.gif
It's so smooth. Thank you

**Comment by truizlop** [comment]
It is in this same repository:
https://github.com/truizlop/FABRevealLayout/blob/master/app/src/main/java/com/truizlop/fabreveallayoutsample/MainActivity.java

**Comment by fukemy** [comment]
thanks you. really nice :)
